### ISSUE TITLE
Add README.dev.md file

### ISSUE THREAD

**Issue by abelsiqueira** [TNO-Tulipa/TulipaBulb.jl#1]
This file should describe how to setup the environment to develop the package. For instance, installing pre-commit.
Check https://github.com/abelsiqueira/PlaygroundWithGit.jl for example.

**Comment by clizbe** [comment]
Is this not a duplicate of #5?

**Comment by clizbe** [comment]
Oh nvm I didn't realize GIT numbers both Issues and Pull Requests.
