### ISSUE TITLE
Change the Tulipa name :'(

### ISSUE THREAD

**Issue by g-moralesespana** [TNO-Tulipa/TulipaBulb.jl#27]
On August 16 we came up with different options to think about:

- FlexBloom
- EnergyBloom
- BloomEn

**Comment by clizbe** [comment]
- TightEnergy
- TightEn

**Comment by g-moralesespana** [comment]
I do not like the term Tight in the name, because it is much more than that.

**Comment by abelsiqueira** [comment]
What are some keywords related to the model?

**Comment by abelsiqueira** [comment]
Out _robot_ friend suggested TEMPEST: Tight Energy Model for Polytemporal Efficient System Tuning

**Comment by g-moralesespana** [comment]
We were not too keen on an acronym but some keywords would be: energy systems, reliable, flexible, computationally efficient

**Comment by clizbe** [comment]
Yes preferably not an acronym.

We want it to be:
- Memorable
- Googlable
- Pronounceable
- Nice to say and read
- Related to energy and/or sustainability/nature
- A bonus is giving people an idea of what it does, as @suvayu advocates

**Comment by clizbe** [comment]
Sven (scientifically validated energy) but just call it Sven.

**Comment by gnawin** [comment]
> Sven (scientifically validated energy) but just call it Sven or SvenModel.

Sven is a first name in the Netherlands. So I'm not sure if it's a good idea to use it.

**Comment by suvayu** [comment]
> Sven is a first name in the Netherlands. So I'm not sure if it's a good idea to use it.
Perfect opportunity to anthropomorphise an energy system model ;)

**Comment by suvayu** [comment]
Just an observation, I've noticed quite some open source projects nowadays add an explanation/history of the project name in the README.  So there might be some room for symbolism in the name, especially if you can support it with a nice logo.

**Comment by datejada** [comment]
I agree @suvayu; we need to put together a good "Ethos" with all the elements @clizbe mentions. I'm still blocked; let's see if, in Colombia and on vacation, I can think of something :/

**Comment by clizbe** [comment]
Other ideas:
- BloomPRO: Peer-reviewed Optimisation
- Samson, Samson Energy, Samson Energy Model (i.e. Samson and Goliath - small model, big problems)
- Evolve, Evolve Energy, Energy Evolution (referring that the model changes and builds with new research, although maybe not because might imply it's a genetic algorithm)
- Bar, Bar Energy, Bar Energy Model (we're setting/raising the bar! :D)
- DrEnergy (or some reference that it's peer-reviewed, PhD research, etc)
- Sound Energy (scientifically sound! but might be confusing since you also hear sound)

**Comment by clizbe** [comment]
Or how about onomatopoeias? 
- Buzz
- Zap
- Switch (already exists - have to make more unique)
- Snap

**Comment by clizbe** [comment]
EnergyBoom or BoomEnergyModel - and call it Boom for short

**Comment by clizbe** [comment]
Bloom Energy Model - call it Bloom for short

**Comment by clizbe** [comment]
Diego drinking on the beach in Columbia has resolved this issue.\
Tulipa it is! With some add-ons like Energy Model, Clustering, etc.\
Org: **Tulipa Energy**\
Main package: **Tulipa Energy Model**
