### ISSUE TITLE
YAML and JSON formatting

### ISSUE THREAD

**Issue by abelsiqueira** [TNO-Tulipa/TulipaBulb.jl#40]
EditorConfig is configured to use 4 spaces, but YAML and JSON files were created with 2 spaces.
Since the formatting of these files is not checked - only correctness (hopefully) - these are not enforced.
However, when using an editor, especially when "format on save" is enabled, the editor tries to force 4 spaces.

We should try to find a formatter/linter for yaml and json. Either way, we should fix the behaviour with one of two options:

Option 1:

- Configure `.editorconfig` to use 2 spaces for  yaml and json

Option 2

- Update all yaml and json files to use 4 spaces

**Comment by abelsiqueira** [comment]
Available pre-commit hooks: https://pre-commit.com/hooks.html
Possible yaml formatter: https://github.com/adrienverge/yamllint
Possible json formatted: Option `pretty-format-json` from https://github.com/pre-commit/pre-commit-hooks (which includes the basic hooks).

**Comment by abelsiqueira** [comment]
Actually, we already use json formatting, so it is just a matter of adding the indent size to it and making sure it is consistent with the editorconfig configuration.

**Comment by clizbe** [comment]
Don't know what the difference is, but 4 spaces is my preference aesthetically. /shrug
